spring:
  application:
    name: Jpa_homework , homework
  datasource:
    url: jdbc:postgresql://157.245.207.70:5433/postgres   # change localhost to postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080